### ISSUE TITLE
whitelist

### ISSUE THREAD

**Issue by chernots** [devnulli/EvlWatcher#96] opened 2022-04-21 09:00 UTC
Hi, 
why is the whitelist being overwritten by banlist?
![bug](https://user-images.githubusercontent.com/68702990/164419600-1c3a69b1-9e1f-4c65-967f-cec621a0b731.png)
 
 That actually same IPs...

**Comment by devnulli** [comment] 2022-05-06 17:18
Hi, is this issue still present in the latest Version
Which version are you using?
(Possible duplicate of #64 )

**Closed as completed** 2022-05-11 11:16 UTC
Labels: waiting
