### ISSUE TITLE
Tester

### ISSUE THREAD

**Issue by shimuldn** [devnulli/EvlWatcher#19] opened 2020-08-03 13:50 UTC
I have few 2019 servers and i can test.

Now using v1.4 and V2.0 alpha.
Alpha seems unstable.

Let me know how can I help.

**Comment by devnulli** [comment] 2020-10-28 21:06
hi, thanks a lot for you offer. ill tag you in the tester issue. duplicate of #14

**Closed by devnulli** 2020-10-28 21:06 UTC
Labels: duplicate
