### ISSUE TITLE
Copying IP address

### ISSUE THREAD

**Issue by olluz** [devnulli/EvlWatcher#121] opened 2023-09-17 22:19 UTC
Hi,
thanks a lot for the app.
Your app was not being listed as an alternative to Fail2Ban on alternativeto.net, but I fixed it.

Anyway, it would really cool if there would be a way to copy the currently banned IP addresses and not having to type them one by one (for example for futher investigation)

Thanks!

**Comment by RickkeeC** [comment] 2023-10-25 22:45
Are the permanently banned IP's stored in the registry, pulled from the event log or firewall logs?
How, where is the list stored, please?  I've acquired several hundred and would like to put them in a separate firewall rule that I can export and import across servers. - Thanks!

**Comment by RickkeeC** [comment] 2023-10-26 01:31
Well duh, the issue is resolved. The permanent IP's can be found in the config.html  The temporary bans can be found in firewall rule or security event log.  
 
    <Banlist>45.141.87.6;45.141.87.9;45.141.87.7;45.141.87.10;71.43.19.115;99.75.135.58;98.55.247.158;</Banlist>

**Comment by devnulli** [comment] 2023-10-26 17:19
hehe. closing

**Comment by olluz** [comment] 2023-10-26 20:44
I was hoping more for something like:

adding a (right) click handler on your selected listview items and then 
Clipboard.SetText(ListView.SelectedItems().Content.ToString())

if it is not too much to ask.

**Comment by devnulli** [comment] 2023-10-29 19:55
can do

**Closed** 2024-01-20 12:15 UTC
Labels: enhancement, staging
