### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by rotame** [devnulli/EvlWatcher#109] opened 2023-01-28 14:01 UTC
Hi 

Windows Server 2019 STD BUILD 1809
From console of app :
1/28/2023 3:59:14 PM - [Error]: Collection was modified; enumeration operation may not execute.

From Windows EVentviewer :
Log Name:      Application
Source:        EvlWatcher
Date:          1/28/2023 4:00:16 PM
Event ID:      0
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      OctanaServer
Description:
Collection was modified; enumeration operation may not execute.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="EvlWatcher" />
    <EventID Qualifiers="0">0</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-01-28T14:00:16.782961800Z" />
    <EventRecordID>28033</EventRecordID>
    <Channel>Application</Channel>
    <Computer>OctanaServer</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Collection was modified; enumeration operation may not execute.</Data>
  </EventData>
</Event>

**Comment by did-vmonroig** [comment] 2023-02-07 19:53
Seems a duplicated of #88.

**Comment by devnulli** [comment] 2023-05-18 13:04
duplicate of #88

**Closed by devnulli** 2023-05-18 13:04 UTC
