### ISSUE TITLE
EvlWatcher Service has stopped working

### ISSUE THREAD

**Issue by derodevil** [devnulli/EvlWatcher#55] opened 2021-02-11 09:26 UTC
I try on Windows Server 2016. A console shows this error before the application shown.

```
Unhandled Exception: System.ServiceModel.AddressAlreadyInUseException: Cannot listen on pipe name 'net.pipe://localhost/' because another pipe endpoint is already listening on that name. ---> System.IO.PipeException: Cannot listen on pipe name 'net.pipe://localhost/' because another pipe endpoint is already listening on that name.
   --- End of inner exception stack trace ---
   at System.ServiceModel.Channels.PipeConnectionListener.Listen()
   at System.ServiceModel.Channels.ExclusiveNamedPipeTransportManager.OnOpen()
   at System.ServiceModel.Channels.TransportManager.Open(TransportChannelListener channelListener)
   at System.ServiceModel.Channels.TransportManagerContainer.Open(SelectTransportManagersCallback selectTransportManagerCallback)
   at System.ServiceModel.Channels.TransportChannelListener.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.ConnectionOrientedTransportChannelListener.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.NamedPipeChannelListener`2.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at EvlWatcher.EvlWatcher.OnStart(String[] args)
   at EvlWatcher.EvlWatcher.Main(String[] args)
```

**Comment by devnulli** [comment] 2021-02-12 07:28
@derodevil 
this can happen when: 
- a second instance of EvlWatcher is already running. for example, when you manualy start evlwatcher.exe while also running as service
- another service application also uses the same named-pipe 

could you answer the following questions?
- did the service crash righ at startup (what i guess), or after running for a while (what would be strange)
- can you reproduce it?
- if yes, can you check services.msc or the task manager if another instance is running. 

- if none of the above, we might have to switch control channel, because some other app on your server uses named pipes incorrectly. - apps known to do that are for example license servers from a renowned CAD company

**Comment by devnulli** [comment] 2021-02-12 07:29
whoops accidentally closed it :D

**Closed** 2021-02-19 21:17 UTC
Labels: not reproducable
